# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """
[ $os $username](bg:#27a1b9 fg:black)\
[](fg:#27a1b9 bg:#769ff0)\
$directory\
[](fg:#769ff0)\
[ $git_branch $git_status]()\
$sudo\
\n[└](fg:#1c668d bold)$status$character
"""

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[$user]($style)'

[sudo]
disabled = false
symbol = "SUDO"
style = "bold red"
format = '[$symbol]($style)'

[status]
disabled = false
format = '[ ($status)](bold fg:red)'

[directory]
style = "fg:black bg:#769ff0"
format = "[$read_only$path]($style)"
repo_root_format = '[ $read_only]($style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)'
truncation_length = 7
read_only = "󰌾 "
repo_root_style = "bold fg:black bg:#769ff0"
truncation_symbol = "…/"
home_symbol = '~'
use_os_path_sep = true

[character]
success_symbol = '[ \$](bold green)'
error_symbol = '[ \$](bold red)'

[hostname]
ssh_only = false
ssh_symbol = " "
style = "fg:crust"
format = '@(bold)[$ssh_symbol](bold)[$hostname]($style)'
#trim_at = '.companyname.com'
disabled = false

[git_status]
style = "fg:green"

[git_branch]
symbol = " "
style = "fg:green"
format = "[$symbol$branch]($style)"

[time]
disabled = false
time_format = "%R"
style = "fg:black bg:purple"
format = '[  $time]($style)[](fg:purple)'

[fill]
symbol = '─'
style = "fg:lavender"

# symbols
[aws]
symbol = "  "
style = "bg:#394260 fg:green"

[buf]
symbol = " "
style = "bg:#394260 fg:green"

[bun]
symbol = " "
style = "bg:#394260 fg:green"

[c]
symbol = " "
style = "bg:#394260 fg:green"

[cpp]
symbol = " "
style = "bg:#394260 fg:green"

[cmake]
symbol = " "
style = "bg:#394260 fg:green"

[conda]
symbol = " "
style = "bg:#394260 fg:green"

[crystal]
symbol = " "
style = "bg:#394260 fg:green"

[dart]
symbol = " "
style = "bg:#394260 fg:green"

[deno]
symbol = " "
style = "bg:#394260 fg:green"

[docker_context]
symbol = " "
style = "bg:#394260 fg:green"

[elixir]
symbol = " "
style = "bg:#394260 fg:green"

[elm]
symbol = " "
style = "bg:#394260 fg:green"

[fennel]
symbol = " "
style = "bg:#394260 fg:green"

[fossil_branch]
symbol = " "
style = "bg:#394260 fg:green"

[gcloud]
symbol = "  "
style = "bg:#394260 fg:green"

[git_commit]
tag_symbol = '  '
style = "bg:#394260 fg:green"

[golang]
symbol = " "
style = "bg:#394260 fg:green"

[guix_shell]
symbol = " "
style = "bg:#394260 fg:green"

[haskell]
symbol = " "
style = "bg:#394260 fg:green"

[haxe]
symbol = " "
style = "bg:#394260 fg:green"

[hg_branch]
symbol = " "
style = "bg:#394260 fg:green"

[java]
symbol = " "
style = "bg:#394260 fg:green"

[julia]
symbol = " "
style = "bg:#394260 fg:green"

[kotlin]
symbol = " "
style = "bg:#394260 fg:green"

[lua]
symbol = " "
style = "bg:#394260 fg:green"

[memory_usage]
symbol = "󰍛 "
style = "bg:#394260 fg:green"

[meson]
symbol = "󰔷 "
style = "bg:#394260 fg:green"

[nim]
symbol = "󰆥 "
style = "bg:#394260 fg:green"

[nix_shell]
symbol = " "
style = "bg:#394260 fg:green"

[nodejs]
symbol = " "
style = "bg:#394260 fg:green"

[ocaml]
symbol = " "
style = "bg:#394260 fg:green"

[os]
disabled = false
style = "bg:red fg:crust"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
