# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'christoomey/vim-tmux-navigator'

# set theme
#set -g @plugin 'catppucin/tmux'
#run ~/.tmux/plugins/tmux/catppuccin.tmux
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_transparent 1
set -g @tokyo-night-tmux_show_hostname 1
set -g @tokyo-night-tmux_show_path 1
set -g @tokyo-night-tmux_path_format full # 'relative' or 'full'


# fix colors
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-ghostty:Tc"
set-option -ga terminal-overrides ",*:Tc"


# enable mouse support
set -g mouse on

# initialize package manager
run '~/.tmux/plugins/tpm/tpm'

